name = "ISVD"
uuid = "0de75c66-c0d4-11e8-3de9-d1632eed9267"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
Test = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
